# version: '3.8'

services:
  db:
    image: postgres:15
    container_name: qt_postgres
    restart: always
    env_file:              
      - .env
    environment:
      - POSTGRES_USER=${LOCAL_DB_USER}
      - POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}
      - POSTGRES_DB=${LOCAL_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${LOCAL_DB_USER}", "-d", "${LOCAL_DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
      
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"


volumes:
  postgres_data: